### ISSUE TITLE
Does not support multiple modals

### ISSUE THREAD

**Issue by stubbies** [joaopereirawd/animatedModal.js#17] opened 2015-11-12 19:48 UTC
I have 2 modals with different `modalTarget` but the first one does not close because `settings.modalTarget` get's the last target.

**Comment by vitschlesinger** [comment] 2015-12-01 13:16
I had the same problem, fixed with this solution - try it: http://d.pr/i/1bCr1

**Comment by ErnestBrandi** [comment] 2015-12-11 00:02
Dead link! Can you post it again please :)

**Comment by mgreiner28** [comment] 2016-02-10 16:39
I'm currently having the same issue. Has this ever been solved??

**Comment by chrux** [comment] 2016-02-10 17:03
I was having the same issue, the solution was that I had to explicity specify the target

```
$("#demo02").animatedModal({
                modalTarget:'modal-02'
});
```

**Comment by mgreiner28** [comment] 2016-02-10 18:17
Thank You. Greatly appreciated!

**Comment by sunilw** [comment] 2016-04-06 00:06
Possibly a bug, but I'm not sure.

When I alter the modalTarget I get an interesting and undesirable result: the opacity value for the modal is '0' by the time the animation has completed.

I'm not at the point yet where I'm trying to replicate the issue though.

**Comment by mmatthews1981** [comment] 2016-05-22 07:40
using the solution @chrux gave, I've got 5 modals running on my page, which makes me happy. Unfortunately, I'm completely addicted to modals, and I want more of them on my page. The problem is, I've discovered that modals only work in the first DOM node they're called on. If I put modals in my <header>, I can't put them in my <main>.

**Comment by shahin059** [comment] 2018-10-07 09:30
I am trying to add two different modals in a same page . but second modal is not working . Can anyone help me ?

**Comment by joaopereirawd** [comment] 2018-12-19 13:08
No more needed to specify **modalTarget**
You may consider update your animatedModal script! 

https://github.com/joaopereirawd/animatedModal.js/commit/e627ed94ce8d41b0964111a97c8617d86eea7d0b

**Closed as completed** 2018-12-19 13:08 UTC
